from beta_bot.controller.fetch_crypto import fetch_multiple_coins
from beta_bot.controller.calculate_indicator import heikinashi, adaptiveTrendFinder, calculateSTCIndicator, parabolic_sar_ma_strategy
from beta_bot.controller.trade_management import main_trade_func
from beta_bot.controller.ml_model import predict_future
